// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Memlocal>>
abstract class Memlocal implements RustOpaqueInterface {
  /// Total stored memories (None = all types).
  Future<int> memoryCount();

  /// Open an in-memory engine. Phase 0 smoke entry point.
  static Future<Memlocal> openInMemory({required int dimensions}) => RustLib
      .instance
      .api
      .crateApiSkeletonMemlocalOpenInMemory(dimensions: dimensions);
}
